package com.movieapi.model;

import jakarta.validation.constraints.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Movie entity representing a movie in the catalog.
 * Contains validation constraints to ensure data integrity.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Movie {

    /**
     * Unique identifier for the movie.
     * Auto-generated by the service layer.
     */
    private Long id;

    /**
     * Title of the movie.
     * Must not be blank.
     */
    @NotBlank(message = "Title is required and cannot be blank")
    private String title;

    /**
     * Description of the movie.
     * Must not be blank.
     */
    @NotBlank(message = "Description is required and cannot be blank")
    private String description;

    /**
     * Year when the movie was released.
     * Must be between 1888 (first motion picture) and current year + 5 (for upcoming releases).
     */
    @NotNull(message = "Release year is required")
    @Min(value = 1888, message = "Release year must be 1888 or later")
    @Max(value = 2031, message = "Release year cannot be more than 5 years in the future")
    private Integer releaseYear;

    /**
     * Genre of the movie (e.g., Action, Drama, Comedy).
     * Must not be blank.
     */
    @NotBlank(message = "Genre is required and cannot be blank")
    private String genre;

    /**
     * Rating of the movie (0.0 to 10.0).
     * Optional field.
     */
    @Min(value = 0, message = "Rating must be at least 0")
    @Max(value = 10, message = "Rating must be at most 10")
    private Double rating;
}
